### ISSUE TITLE
defaults.yaml in PanWriterUserData partially ignored

### ISSUE THREAD

**Issue by Skeeve** [mb21/panwriter#132]
I put this into my `default.yaml` in `PanWriterUserData`

```yaml
---
mainfont: American Typewriter
output:
  latex:
    toc: true
---
```

The toc part is working and I get my toc in my document.

the mainfont works in the preview when I have it in my document, but not when it's in the `default.yaml`.

It is not taken into account when exporting to PDF. Neither in `default.yaml` nor in the document (see #131)

I'm using

Mac OS 13.1
pandoc 3.1
panWriter 0.8.5
