### ISSUE TITLE
Export to reveal.js

### ISSUE THREAD

**Issue by anschmieg** [mb21/panwriter#142]
Hi, thanks for all your hard work on PanWriter! I am experiencing some difficulty exporting to **reveal.js**. I could not find an option to specify this in the **YAML metadata block**, and it is not listed under _Format_ in the **export dialog**.

More generally, I think it would be useful to have an option to specify certain arguments for a given file. Maybe this is possible by using a Lua filter?

**Comment by mb21** [comment]
Hello!

That should already work, I just improved the docs on that: https://github.com/mb21/panwriter/pull/143
Does that make things clearer?

i.e. this should work:

```
---
title: my title
output:
  html:
    to: revealjs
---

# test

# test2
```
